// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.19.4
// source: proto/plan.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryOperator int32

const (
	BinaryOperator_ADD BinaryOperator = 0
	BinaryOperator_SUB BinaryOperator = 1
	BinaryOperator_MUL BinaryOperator = 2
	BinaryOperator_DIV BinaryOperator = 3
	BinaryOperator_EQ  BinaryOperator = 4
	BinaryOperator_NE  BinaryOperator = 5
	BinaryOperator_LT  BinaryOperator = 6
	BinaryOperator_LE  BinaryOperator = 7
	BinaryOperator_GT  BinaryOperator = 8
	BinaryOperator_GE  BinaryOperator = 9
	BinaryOperator_AND BinaryOperator = 10
	BinaryOperator_OR  BinaryOperator = 11
)

// Enum value maps for BinaryOperator.
var (
	BinaryOperator_name = map[int32]string{
		0:  "ADD",
		1:  "SUB",
		2:  "MUL",
		3:  "DIV",
		4:  "EQ",
		5:  "NE",
		6:  "LT",
		7:  "LE",
		8:  "GT",
		9:  "GE",
		10: "AND",
		11: "OR",
	}
	BinaryOperator_value = map[string]int32{
		"ADD": 0,
		"SUB": 1,
		"MUL": 2,
		"DIV": 3,
		"EQ":  4,
		"NE":  5,
		"LT":  6,
		"LE":  7,
		"GT":  8,
		"GE":  9,
		"AND": 10,
		"OR":  11,
	}
)

func (x BinaryOperator) Enum() *BinaryOperator {
	p := new(BinaryOperator)
	*p = x
	return p
}

func (x BinaryOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BinaryOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plan_proto_enumTypes[0].Descriptor()
}

func (BinaryOperator) Type() protoreflect.EnumType {
	return &file_proto_plan_proto_enumTypes[0]
}

func (x BinaryOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BinaryOperator.Descriptor instead.
func (BinaryOperator) EnumDescriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{0}
}

// 数据类型
type DataType int32

const (
	DataType_INT64   DataType = 0
	DataType_FLOAT64 DataType = 1
	DataType_BOOL    DataType = 2
	DataType_UTF8    DataType = 3
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "INT64",
		1: "FLOAT64",
		2: "BOOL",
		3: "UTF8",
	}
	DataType_value = map[string]int32{
		"INT64":   0,
		"FLOAT64": 1,
		"BOOL":    2,
		"UTF8":    3,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plan_proto_enumTypes[1].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_proto_plan_proto_enumTypes[1]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{1}
}

// Plan 版本 v1
type Plan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanVersion uint32 `protobuf:"varint,1,opt,name=plan_version,json=planVersion,proto3" json:"plan_version,omitempty"` // 当前为 1
	Root        *Node  `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
}

func (x *Plan) Reset() {
	*x = Plan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetPlanVersion() uint32 {
	if x != nil {
		return x.PlanVersion
	}
	return 0
}

func (x *Plan) GetRoot() *Node {
	if x != nil {
		return x.Root
	}
	return nil
}

// 节点定义
type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Kind:
	//
	//	*Node_MemoryScan
	//	*Node_Project
	//	*Node_Filter
	//	*Node_WithColumns
	//	*Node_Limit
	Kind isNode_Kind `protobuf_oneof:"kind"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (m *Node) GetKind() isNode_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *Node) GetMemoryScan() *MemoryScan {
	if x, ok := x.GetKind().(*Node_MemoryScan); ok {
		return x.MemoryScan
	}
	return nil
}

func (x *Node) GetProject() *Project {
	if x, ok := x.GetKind().(*Node_Project); ok {
		return x.Project
	}
	return nil
}

func (x *Node) GetFilter() *Filter {
	if x, ok := x.GetKind().(*Node_Filter); ok {
		return x.Filter
	}
	return nil
}

func (x *Node) GetWithColumns() *WithColumns {
	if x, ok := x.GetKind().(*Node_WithColumns); ok {
		return x.WithColumns
	}
	return nil
}

func (x *Node) GetLimit() *Limit {
	if x, ok := x.GetKind().(*Node_Limit); ok {
		return x.Limit
	}
	return nil
}

type isNode_Kind interface {
	isNode_Kind()
}

type Node_MemoryScan struct {
	MemoryScan *MemoryScan `protobuf:"bytes,10,opt,name=memory_scan,json=memoryScan,proto3,oneof"`
}

type Node_Project struct {
	Project *Project `protobuf:"bytes,11,opt,name=project,proto3,oneof"`
}

type Node_Filter struct {
	Filter *Filter `protobuf:"bytes,12,opt,name=filter,proto3,oneof"`
}

type Node_WithColumns struct {
	WithColumns *WithColumns `protobuf:"bytes,13,opt,name=with_columns,json=withColumns,proto3,oneof"`
}

type Node_Limit struct {
	Limit *Limit `protobuf:"bytes,16,opt,name=limit,proto3,oneof"`
}

func (*Node_MemoryScan) isNode_Kind() {}

func (*Node_Project) isNode_Kind() {}

func (*Node_Filter) isNode_Kind() {}

func (*Node_WithColumns) isNode_Kind() {}

func (*Node_Limit) isNode_Kind() {}

// Memory Scan（从输入 Arrow 读取）
type MemoryScan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColumnNames []string `protobuf:"bytes,1,rep,name=column_names,json=columnNames,proto3" json:"column_names,omitempty"`
}

func (x *MemoryScan) Reset() {
	*x = MemoryScan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoryScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryScan) ProtoMessage() {}

func (x *MemoryScan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryScan.ProtoReflect.Descriptor instead.
func (*MemoryScan) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryScan) GetColumnNames() []string {
	if x != nil {
		return x.ColumnNames
	}
	return nil
}

// Project（选择列）
type Project struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input       *Node   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Expressions []*Expr `protobuf:"bytes,2,rep,name=expressions,proto3" json:"expressions,omitempty"`
}

func (x *Project) Reset() {
	*x = Project{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{3}
}

func (x *Project) GetInput() *Node {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Project) GetExpressions() []*Expr {
	if x != nil {
		return x.Expressions
	}
	return nil
}

// Filter（过滤）
type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input     *Node `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Predicate *Expr `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{4}
}

func (x *Filter) GetInput() *Node {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Filter) GetPredicate() *Expr {
	if x != nil {
		return x.Predicate
	}
	return nil
}

// WithColumns（添加/修改列）
type WithColumns struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input       *Node   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Expressions []*Expr `protobuf:"bytes,2,rep,name=expressions,proto3" json:"expressions,omitempty"`
}

func (x *WithColumns) Reset() {
	*x = WithColumns{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithColumns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithColumns) ProtoMessage() {}

func (x *WithColumns) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithColumns.ProtoReflect.Descriptor instead.
func (*WithColumns) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{5}
}

func (x *WithColumns) GetInput() *Node {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *WithColumns) GetExpressions() []*Expr {
	if x != nil {
		return x.Expressions
	}
	return nil
}

// Limit（限制行数）
type Limit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input *Node  `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	N     uint64 `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
}

func (x *Limit) Reset() {
	*x = Limit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{6}
}

func (x *Limit) GetInput() *Node {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Limit) GetN() uint64 {
	if x != nil {
		return x.N
	}
	return 0
}

// 表达式
type Expr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//
	//	*Expr_Col
	//	*Expr_Lit
	//	*Expr_Binary
	//	*Expr_Alias
	//	*Expr_IsNull
	Kind isExpr_Kind `protobuf_oneof:"kind"`
}

func (x *Expr) Reset() {
	*x = Expr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr) ProtoMessage() {}

func (x *Expr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr.ProtoReflect.Descriptor instead.
func (*Expr) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{7}
}

func (m *Expr) GetKind() isExpr_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *Expr) GetCol() *Column {
	if x, ok := x.GetKind().(*Expr_Col); ok {
		return x.Col
	}
	return nil
}

func (x *Expr) GetLit() *Literal {
	if x, ok := x.GetKind().(*Expr_Lit); ok {
		return x.Lit
	}
	return nil
}

func (x *Expr) GetBinary() *BinaryExpr {
	if x, ok := x.GetKind().(*Expr_Binary); ok {
		return x.Binary
	}
	return nil
}

func (x *Expr) GetAlias() *Alias {
	if x, ok := x.GetKind().(*Expr_Alias); ok {
		return x.Alias
	}
	return nil
}

func (x *Expr) GetIsNull() *IsNull {
	if x, ok := x.GetKind().(*Expr_IsNull); ok {
		return x.IsNull
	}
	return nil
}

type isExpr_Kind interface {
	isExpr_Kind()
}

type Expr_Col struct {
	Col *Column `protobuf:"bytes,1,opt,name=col,proto3,oneof"`
}

type Expr_Lit struct {
	Lit *Literal `protobuf:"bytes,2,opt,name=lit,proto3,oneof"`
}

type Expr_Binary struct {
	Binary *BinaryExpr `protobuf:"bytes,3,opt,name=binary,proto3,oneof"`
}

type Expr_Alias struct {
	Alias *Alias `protobuf:"bytes,4,opt,name=alias,proto3,oneof"`
}

type Expr_IsNull struct {
	IsNull *IsNull `protobuf:"bytes,5,opt,name=is_null,json=isNull,proto3,oneof"`
}

func (*Expr_Col) isExpr_Kind() {}

func (*Expr_Lit) isExpr_Kind() {}

func (*Expr_Binary) isExpr_Kind() {}

func (*Expr_Alias) isExpr_Kind() {}

func (*Expr_IsNull) isExpr_Kind() {}

// 列引用
type Column struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Column) Reset() {
	*x = Column{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{8}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 字面量
type Literal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*Literal_IntVal
	//	*Literal_FloatVal
	//	*Literal_BoolVal
	//	*Literal_StringVal
	//	*Literal_NullVal
	Value isLiteral_Value `protobuf_oneof:"value"`
}

func (x *Literal) Reset() {
	*x = Literal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Literal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Literal) ProtoMessage() {}

func (x *Literal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Literal.ProtoReflect.Descriptor instead.
func (*Literal) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{9}
}

func (m *Literal) GetValue() isLiteral_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Literal) GetIntVal() int64 {
	if x, ok := x.GetValue().(*Literal_IntVal); ok {
		return x.IntVal
	}
	return 0
}

func (x *Literal) GetFloatVal() float64 {
	if x, ok := x.GetValue().(*Literal_FloatVal); ok {
		return x.FloatVal
	}
	return 0
}

func (x *Literal) GetBoolVal() bool {
	if x, ok := x.GetValue().(*Literal_BoolVal); ok {
		return x.BoolVal
	}
	return false
}

func (x *Literal) GetStringVal() string {
	if x, ok := x.GetValue().(*Literal_StringVal); ok {
		return x.StringVal
	}
	return ""
}

func (x *Literal) GetNullVal() *NullValue {
	if x, ok := x.GetValue().(*Literal_NullVal); ok {
		return x.NullVal
	}
	return nil
}

type isLiteral_Value interface {
	isLiteral_Value()
}

type Literal_IntVal struct {
	IntVal int64 `protobuf:"varint,1,opt,name=int_val,json=intVal,proto3,oneof"`
}

type Literal_FloatVal struct {
	FloatVal float64 `protobuf:"fixed64,2,opt,name=float_val,json=floatVal,proto3,oneof"`
}

type Literal_BoolVal struct {
	BoolVal bool `protobuf:"varint,3,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

type Literal_StringVal struct {
	StringVal string `protobuf:"bytes,4,opt,name=string_val,json=stringVal,proto3,oneof"`
}

type Literal_NullVal struct {
	NullVal *NullValue `protobuf:"bytes,5,opt,name=null_val,json=nullVal,proto3,oneof"`
}

func (*Literal_IntVal) isLiteral_Value() {}

func (*Literal_FloatVal) isLiteral_Value() {}

func (*Literal_BoolVal) isLiteral_Value() {}

func (*Literal_StringVal) isLiteral_Value() {}

func (*Literal_NullVal) isLiteral_Value() {}

type NullValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullValue) Reset() {
	*x = NullValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullValue) ProtoMessage() {}

func (x *NullValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullValue.ProtoReflect.Descriptor instead.
func (*NullValue) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{10}
}

// 二元表达式
type BinaryExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Left  *Expr          `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Op    BinaryOperator `protobuf:"varint,2,opt,name=op,proto3,enum=polars_bridge.BinaryOperator" json:"op,omitempty"`
	Right *Expr          `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
}

func (x *BinaryExpr) Reset() {
	*x = BinaryExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinaryExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryExpr) ProtoMessage() {}

func (x *BinaryExpr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryExpr.ProtoReflect.Descriptor instead.
func (*BinaryExpr) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{11}
}

func (x *BinaryExpr) GetLeft() *Expr {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *BinaryExpr) GetOp() BinaryOperator {
	if x != nil {
		return x.Op
	}
	return BinaryOperator_ADD
}

func (x *BinaryExpr) GetRight() *Expr {
	if x != nil {
		return x.Right
	}
	return nil
}

// 别名
type Alias struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expr *Expr  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Alias) Reset() {
	*x = Alias{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alias) ProtoMessage() {}

func (x *Alias) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alias.ProtoReflect.Descriptor instead.
func (*Alias) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{12}
}

func (x *Alias) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Alias) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 空值检查
type IsNull struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expr *Expr `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
}

func (x *IsNull) Reset() {
	*x = IsNull{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plan_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsNull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsNull) ProtoMessage() {}

func (x *IsNull) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plan_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsNull.ProtoReflect.Descriptor instead.
func (*IsNull) Descriptor() ([]byte, []int) {
	return file_proto_plan_proto_rawDescGZIP(), []int{13}
}

func (x *IsNull) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

var File_proto_plan_proto protoreflect.FileDescriptor

var file_proto_plan_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x22, 0x52, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6c, 0x61,
	0x6e, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x70, 0x6c, 0x61, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x04,
	0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6c,
	0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x72, 0x6f, 0x6f, 0x74, 0x22, 0xbd, 0x02, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3c,
	0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x63, 0x61, 0x6e, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x63, 0x61, 0x6e, 0x48, 0x00,
	0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x32, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x2f, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x3f, 0x0a, 0x0c, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73,
	0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x73, 0x12, 0x2c, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x4a, 0x04, 0x08, 0x32, 0x10, 0x64, 0x4a, 0x05,
	0x08, 0x64, 0x10, 0x96, 0x01, 0x22, 0x2f, 0x0a, 0x0a, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53,
	0x63, 0x61, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x6b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x35, 0x0a, 0x0b,
	0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x66, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x29, 0x0a,
	0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x31, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f,
	0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x70, 0x72,
	0x52, 0x09, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x6f, 0x0a, 0x0b, 0x57,
	0x69, 0x74, 0x68, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6c, 0x61,
	0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6c,
	0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x52,
	0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x40, 0x0a, 0x05,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x6e, 0x22, 0x87,
	0x02, 0x0a, 0x04, 0x45, 0x78, 0x70, 0x72, 0x12, 0x29, 0x0a, 0x03, 0x63, 0x6f, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x63,
	0x6f, 0x6c, 0x12, 0x2a, 0x0a, 0x03, 0x6c, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e,
	0x4c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x69, 0x74, 0x12, 0x33,
	0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x42,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x2e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x48, 0x00, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x12, 0x30, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x2e, 0x49, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x06, 0x69, 0x73, 0x4e,
	0x75, 0x6c, 0x6c, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x4a, 0x04, 0x08, 0x32, 0x10,
	0x64, 0x4a, 0x05, 0x08, 0x64, 0x10, 0x96, 0x01, 0x22, 0x1c, 0x0a, 0x06, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xc1, 0x01, 0x0a, 0x07, 0x4c, 0x69, 0x74, 0x65, 0x72,
	0x61, 0x6c, 0x12, 0x19, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x06, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x1d, 0x0a,
	0x09, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x48, 0x00, 0x52, 0x08, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x08,
	0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00,
	0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x0a, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x09, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x12, 0x35, 0x0a, 0x08, 0x6e, 0x75,
	0x6c, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x4e, 0x75, 0x6c,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x75, 0x6c, 0x6c, 0x56, 0x61,
	0x6c, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x4e, 0x75,
	0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0a, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12,
	0x2d, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x6f,
	0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x29,
	0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x45, 0x78,
	0x70, 0x72, 0x52, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x22, 0x44, 0x0a, 0x05, 0x41, 0x6c, 0x69,
	0x61, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x65, 0x78, 0x70, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x45, 0x78, 0x70, 0x72, 0x52, 0x04, 0x65, 0x78, 0x70, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x31, 0x0a, 0x06, 0x49, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x12, 0x27, 0x0a, 0x04, 0x65, 0x78, 0x70,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73,
	0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x52, 0x04, 0x65, 0x78,
	0x70, 0x72, 0x2a, 0x75, 0x0a, 0x0e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x53, 0x55, 0x42, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x55, 0x4c, 0x10, 0x02, 0x12,
	0x07, 0x0a, 0x03, 0x44, 0x49, 0x56, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x45, 0x51, 0x10, 0x04,
	0x12, 0x06, 0x0a, 0x02, 0x4e, 0x45, 0x10, 0x05, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x54, 0x10, 0x06,
	0x12, 0x06, 0x0a, 0x02, 0x4c, 0x45, 0x10, 0x07, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x54, 0x10, 0x08,
	0x12, 0x06, 0x0a, 0x02, 0x47, 0x45, 0x10, 0x09, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4e, 0x44, 0x10,
	0x0a, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x52, 0x10, 0x0b, 0x2a, 0x36, 0x0a, 0x08, 0x44, 0x61, 0x74,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x36, 0x34, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x54, 0x46, 0x38, 0x10,
	0x03, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x6f, 0x6c, 0x61, 0x72, 0x73, 0x2d, 0x67, 0x6f, 0x2d, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_plan_proto_rawDescOnce sync.Once
	file_proto_plan_proto_rawDescData = file_proto_plan_proto_rawDesc
)

func file_proto_plan_proto_rawDescGZIP() []byte {
	file_proto_plan_proto_rawDescOnce.Do(func() {
		file_proto_plan_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_plan_proto_rawDescData)
	})
	return file_proto_plan_proto_rawDescData
}

var file_proto_plan_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_plan_proto_goTypes = []interface{}{
	(BinaryOperator)(0), // 0: polars_bridge.BinaryOperator
	(DataType)(0),       // 1: polars_bridge.DataType
	(*Plan)(nil),        // 2: polars_bridge.Plan
	(*Node)(nil),        // 3: polars_bridge.Node
	(*MemoryScan)(nil),  // 4: polars_bridge.MemoryScan
	(*Project)(nil),     // 5: polars_bridge.Project
	(*Filter)(nil),      // 6: polars_bridge.Filter
	(*WithColumns)(nil), // 7: polars_bridge.WithColumns
	(*Limit)(nil),       // 8: polars_bridge.Limit
	(*Expr)(nil),        // 9: polars_bridge.Expr
	(*Column)(nil),      // 10: polars_bridge.Column
	(*Literal)(nil),     // 11: polars_bridge.Literal
	(*NullValue)(nil),   // 12: polars_bridge.NullValue
	(*BinaryExpr)(nil),  // 13: polars_bridge.BinaryExpr
	(*Alias)(nil),       // 14: polars_bridge.Alias
	(*IsNull)(nil),      // 15: polars_bridge.IsNull
}
var file_proto_plan_proto_depIdxs = []int32{
	3,  // 0: polars_bridge.Plan.root:type_name -> polars_bridge.Node
	4,  // 1: polars_bridge.Node.memory_scan:type_name -> polars_bridge.MemoryScan
	5,  // 2: polars_bridge.Node.project:type_name -> polars_bridge.Project
	6,  // 3: polars_bridge.Node.filter:type_name -> polars_bridge.Filter
	7,  // 4: polars_bridge.Node.with_columns:type_name -> polars_bridge.WithColumns
	8,  // 5: polars_bridge.Node.limit:type_name -> polars_bridge.Limit
	3,  // 6: polars_bridge.Project.input:type_name -> polars_bridge.Node
	9,  // 7: polars_bridge.Project.expressions:type_name -> polars_bridge.Expr
	3,  // 8: polars_bridge.Filter.input:type_name -> polars_bridge.Node
	9,  // 9: polars_bridge.Filter.predicate:type_name -> polars_bridge.Expr
	3,  // 10: polars_bridge.WithColumns.input:type_name -> polars_bridge.Node
	9,  // 11: polars_bridge.WithColumns.expressions:type_name -> polars_bridge.Expr
	3,  // 12: polars_bridge.Limit.input:type_name -> polars_bridge.Node
	10, // 13: polars_bridge.Expr.col:type_name -> polars_bridge.Column
	11, // 14: polars_bridge.Expr.lit:type_name -> polars_bridge.Literal
	13, // 15: polars_bridge.Expr.binary:type_name -> polars_bridge.BinaryExpr
	14, // 16: polars_bridge.Expr.alias:type_name -> polars_bridge.Alias
	15, // 17: polars_bridge.Expr.is_null:type_name -> polars_bridge.IsNull
	12, // 18: polars_bridge.Literal.null_val:type_name -> polars_bridge.NullValue
	9,  // 19: polars_bridge.BinaryExpr.left:type_name -> polars_bridge.Expr
	0,  // 20: polars_bridge.BinaryExpr.op:type_name -> polars_bridge.BinaryOperator
	9,  // 21: polars_bridge.BinaryExpr.right:type_name -> polars_bridge.Expr
	9,  // 22: polars_bridge.Alias.expr:type_name -> polars_bridge.Expr
	9,  // 23: polars_bridge.IsNull.expr:type_name -> polars_bridge.Expr
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_plan_proto_init() }
func file_proto_plan_proto_init() {
	if File_proto_plan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_plan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoryScan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Project); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithColumns); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Limit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Column); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Literal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinaryExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alias); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plan_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsNull); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_plan_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Node_MemoryScan)(nil),
		(*Node_Project)(nil),
		(*Node_Filter)(nil),
		(*Node_WithColumns)(nil),
		(*Node_Limit)(nil),
	}
	file_proto_plan_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Expr_Col)(nil),
		(*Expr_Lit)(nil),
		(*Expr_Binary)(nil),
		(*Expr_Alias)(nil),
		(*Expr_IsNull)(nil),
	}
	file_proto_plan_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*Literal_IntVal)(nil),
		(*Literal_FloatVal)(nil),
		(*Literal_BoolVal)(nil),
		(*Literal_StringVal)(nil),
		(*Literal_NullVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_plan_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_plan_proto_goTypes,
		DependencyIndexes: file_proto_plan_proto_depIdxs,
		EnumInfos:         file_proto_plan_proto_enumTypes,
		MessageInfos:      file_proto_plan_proto_msgTypes,
	}.Build()
	File_proto_plan_proto = out.File
	file_proto_plan_proto_rawDesc = nil
	file_proto_plan_proto_goTypes = nil
	file_proto_plan_proto_depIdxs = nil
}
