// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/polars_bridge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryOperator int32

const (
	BinaryOperator_ADD BinaryOperator = 0
	BinaryOperator_SUB BinaryOperator = 1
	BinaryOperator_MUL BinaryOperator = 2
	BinaryOperator_DIV BinaryOperator = 3
	BinaryOperator_EQ  BinaryOperator = 4
	BinaryOperator_NE  BinaryOperator = 5
	BinaryOperator_LT  BinaryOperator = 6
	BinaryOperator_LE  BinaryOperator = 7
	BinaryOperator_GT  BinaryOperator = 8
	BinaryOperator_GE  BinaryOperator = 9
	BinaryOperator_AND BinaryOperator = 10
	BinaryOperator_OR  BinaryOperator = 11
	BinaryOperator_MOD BinaryOperator = 12 // 取模运算 %
	BinaryOperator_POW BinaryOperator = 13 // 幂运算 **
	BinaryOperator_XOR BinaryOperator = 14 // 异或运算 ^
)

// Enum value maps for BinaryOperator.
var (
	BinaryOperator_name = map[int32]string{
		0:  "ADD",
		1:  "SUB",
		2:  "MUL",
		3:  "DIV",
		4:  "EQ",
		5:  "NE",
		6:  "LT",
		7:  "LE",
		8:  "GT",
		9:  "GE",
		10: "AND",
		11: "OR",
		12: "MOD",
		13: "POW",
		14: "XOR",
	}
	BinaryOperator_value = map[string]int32{
		"ADD": 0,
		"SUB": 1,
		"MUL": 2,
		"DIV": 3,
		"EQ":  4,
		"NE":  5,
		"LT":  6,
		"LE":  7,
		"GT":  8,
		"GE":  9,
		"AND": 10,
		"OR":  11,
		"MOD": 12,
		"POW": 13,
		"XOR": 14,
	}
)

func (x BinaryOperator) Enum() *BinaryOperator {
	p := new(BinaryOperator)
	*p = x
	return p
}

func (x BinaryOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BinaryOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_polars_bridge_proto_enumTypes[0].Descriptor()
}

func (BinaryOperator) Type() protoreflect.EnumType {
	return &file_proto_polars_bridge_proto_enumTypes[0]
}

func (x BinaryOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BinaryOperator.Descriptor instead.
func (BinaryOperator) EnumDescriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{0}
}

// 数据类型
type DataType int32

const (
	DataType_INT64    DataType = 0
	DataType_INT32    DataType = 1
	DataType_INT16    DataType = 2
	DataType_INT8     DataType = 3
	DataType_UINT64   DataType = 4
	DataType_UINT32   DataType = 5
	DataType_UINT16   DataType = 6
	DataType_UINT8    DataType = 7
	DataType_FLOAT64  DataType = 8
	DataType_FLOAT32  DataType = 9
	DataType_BOOL     DataType = 10
	DataType_UTF8     DataType = 11 // String
	DataType_DATE     DataType = 12
	DataType_DATETIME DataType = 13
	DataType_TIME     DataType = 14
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0:  "INT64",
		1:  "INT32",
		2:  "INT16",
		3:  "INT8",
		4:  "UINT64",
		5:  "UINT32",
		6:  "UINT16",
		7:  "UINT8",
		8:  "FLOAT64",
		9:  "FLOAT32",
		10: "BOOL",
		11: "UTF8",
		12: "DATE",
		13: "DATETIME",
		14: "TIME",
	}
	DataType_value = map[string]int32{
		"INT64":    0,
		"INT32":    1,
		"INT16":    2,
		"INT8":     3,
		"UINT64":   4,
		"UINT32":   5,
		"UINT16":   6,
		"UINT8":    7,
		"FLOAT64":  8,
		"FLOAT32":  9,
		"BOOL":     10,
		"UTF8":     11,
		"DATE":     12,
		"DATETIME": 13,
		"TIME":     14,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_polars_bridge_proto_enumTypes[1].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_proto_polars_bridge_proto_enumTypes[1]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{1}
}

// Plan 版本 v1
type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanVersion   uint32                 `protobuf:"varint,1,opt,name=plan_version,json=planVersion,proto3" json:"plan_version,omitempty"` // 当前为 1
	Root          *Node                  `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_proto_polars_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *Plan) GetPlanVersion() uint32 {
	if x != nil {
		return x.PlanVersion
	}
	return 0
}

func (x *Plan) GetRoot() *Node {
	if x != nil {
		return x.Root
	}
	return nil
}

// 节点定义
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Node_MemoryScan
	//	*Node_CsvScan
	//	*Node_ParquetScan
	//	*Node_Project
	//	*Node_Filter
	//	*Node_WithColumns
	//	*Node_Limit
	Kind          isNode_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_polars_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetKind() isNode_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Node) GetMemoryScan() *MemoryScan {
	if x != nil {
		if x, ok := x.Kind.(*Node_MemoryScan); ok {
			return x.MemoryScan
		}
	}
	return nil
}

func (x *Node) GetCsvScan() *CsvScan {
	if x != nil {
		if x, ok := x.Kind.(*Node_CsvScan); ok {
			return x.CsvScan
		}
	}
	return nil
}

func (x *Node) GetParquetScan() *ParquetScan {
	if x != nil {
		if x, ok := x.Kind.(*Node_ParquetScan); ok {
			return x.ParquetScan
		}
	}
	return nil
}

func (x *Node) GetProject() *Project {
	if x != nil {
		if x, ok := x.Kind.(*Node_Project); ok {
			return x.Project
		}
	}
	return nil
}

func (x *Node) GetFilter() *Filter {
	if x != nil {
		if x, ok := x.Kind.(*Node_Filter); ok {
			return x.Filter
		}
	}
	return nil
}

func (x *Node) GetWithColumns() *WithColumns {
	if x != nil {
		if x, ok := x.Kind.(*Node_WithColumns); ok {
			return x.WithColumns
		}
	}
	return nil
}

func (x *Node) GetLimit() *Limit {
	if x != nil {
		if x, ok := x.Kind.(*Node_Limit); ok {
			return x.Limit
		}
	}
	return nil
}

type isNode_Kind interface {
	isNode_Kind()
}

type Node_MemoryScan struct {
	MemoryScan *MemoryScan `protobuf:"bytes,10,opt,name=memory_scan,json=memoryScan,proto3,oneof"`
}

type Node_CsvScan struct {
	CsvScan *CsvScan `protobuf:"bytes,11,opt,name=csv_scan,json=csvScan,proto3,oneof"`
}

type Node_ParquetScan struct {
	ParquetScan *ParquetScan `protobuf:"bytes,12,opt,name=parquet_scan,json=parquetScan,proto3,oneof"`
}

type Node_Project struct {
	Project *Project `protobuf:"bytes,13,opt,name=project,proto3,oneof"`
}

type Node_Filter struct {
	Filter *Filter `protobuf:"bytes,14,opt,name=filter,proto3,oneof"`
}

type Node_WithColumns struct {
	WithColumns *WithColumns `protobuf:"bytes,15,opt,name=with_columns,json=withColumns,proto3,oneof"`
}

type Node_Limit struct {
	Limit *Limit `protobuf:"bytes,16,opt,name=limit,proto3,oneof"`
}

func (*Node_MemoryScan) isNode_Kind() {}

func (*Node_CsvScan) isNode_Kind() {}

func (*Node_ParquetScan) isNode_Kind() {}

func (*Node_Project) isNode_Kind() {}

func (*Node_Filter) isNode_Kind() {}

func (*Node_WithColumns) isNode_Kind() {}

func (*Node_Limit) isNode_Kind() {}

// Memory Scan（从输入 Arrow 读取）
type MemoryScan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnNames   []string               `protobuf:"bytes,1,rep,name=column_names,json=columnNames,proto3" json:"column_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryScan) Reset() {
	*x = MemoryScan{}
	mi := &file_proto_polars_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryScan) ProtoMessage() {}

func (x *MemoryScan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryScan.ProtoReflect.Descriptor instead.
func (*MemoryScan) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryScan) GetColumnNames() []string {
	if x != nil {
		return x.ColumnNames
	}
	return nil
}

// CSV Scan（从 CSV 文件路径懒加载）
type CsvScan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // 文件路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CsvScan) Reset() {
	*x = CsvScan{}
	mi := &file_proto_polars_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsvScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsvScan) ProtoMessage() {}

func (x *CsvScan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsvScan.ProtoReflect.Descriptor instead.
func (*CsvScan) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *CsvScan) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Parquet Scan（从 Parquet 文件路径懒加载）
type ParquetScan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // 文件路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParquetScan) Reset() {
	*x = ParquetScan{}
	mi := &file_proto_polars_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParquetScan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParquetScan) ProtoMessage() {}

func (x *ParquetScan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParquetScan.ProtoReflect.Descriptor instead.
func (*ParquetScan) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *ParquetScan) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Project（选择列）
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *Node                  `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Expressions   []*Expr                `protobuf:"bytes,2,rep,name=expressions,proto3" json:"expressions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_proto_polars_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *Project) GetInput() *Node {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Project) GetExpressions() []*Expr {
	if x != nil {
		return x.Expressions
	}
	return nil
}

// Filter（过滤）
type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *Node                  `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Predicate     *Expr                  `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_polars_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *Filter) GetInput() *Node {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Filter) GetPredicate() *Expr {
	if x != nil {
		return x.Predicate
	}
	return nil
}

// WithColumns（添加/修改列）
type WithColumns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *Node                  `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Expressions   []*Expr                `protobuf:"bytes,2,rep,name=expressions,proto3" json:"expressions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithColumns) Reset() {
	*x = WithColumns{}
	mi := &file_proto_polars_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithColumns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithColumns) ProtoMessage() {}

func (x *WithColumns) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithColumns.ProtoReflect.Descriptor instead.
func (*WithColumns) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *WithColumns) GetInput() *Node {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *WithColumns) GetExpressions() []*Expr {
	if x != nil {
		return x.Expressions
	}
	return nil
}

// Limit（限制行数）
type Limit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *Node                  `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	N             uint64                 `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limit) Reset() {
	*x = Limit{}
	mi := &file_proto_polars_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *Limit) GetInput() *Node {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Limit) GetN() uint64 {
	if x != nil {
		return x.N
	}
	return 0
}

// 表达式
type Expr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Expr_Col
	//	*Expr_Lit
	//	*Expr_Binary
	//	*Expr_Alias
	//	*Expr_IsNull
	//	*Expr_Not
	//	*Expr_Wildcard
	//	*Expr_Exclude
	//	*Expr_Cast
	//	*Expr_StrLenBytes
	//	*Expr_StrLenChars
	//	*Expr_StrContains
	//	*Expr_StrStartsWith
	//	*Expr_StrEndsWith
	//	*Expr_StrExtract
	//	*Expr_StrReplace
	//	*Expr_StrReplaceAll
	//	*Expr_StrToLowercase
	//	*Expr_StrToUppercase
	//	*Expr_StrToTitlecase
	//	*Expr_StrStripChars
	//	*Expr_StrSlice
	//	*Expr_StrSplit
	//	*Expr_StrPadStart
	//	*Expr_StrPadEnd
	Kind          isExpr_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr) Reset() {
	*x = Expr{}
	mi := &file_proto_polars_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr) ProtoMessage() {}

func (x *Expr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr.ProtoReflect.Descriptor instead.
func (*Expr) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *Expr) GetKind() isExpr_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Expr) GetCol() *Column {
	if x != nil {
		if x, ok := x.Kind.(*Expr_Col); ok {
			return x.Col
		}
	}
	return nil
}

func (x *Expr) GetLit() *Literal {
	if x != nil {
		if x, ok := x.Kind.(*Expr_Lit); ok {
			return x.Lit
		}
	}
	return nil
}

func (x *Expr) GetBinary() *BinaryExpr {
	if x != nil {
		if x, ok := x.Kind.(*Expr_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

func (x *Expr) GetAlias() *Alias {
	if x != nil {
		if x, ok := x.Kind.(*Expr_Alias); ok {
			return x.Alias
		}
	}
	return nil
}

func (x *Expr) GetIsNull() *IsNull {
	if x != nil {
		if x, ok := x.Kind.(*Expr_IsNull); ok {
			return x.IsNull
		}
	}
	return nil
}

func (x *Expr) GetNot() *Not {
	if x != nil {
		if x, ok := x.Kind.(*Expr_Not); ok {
			return x.Not
		}
	}
	return nil
}

func (x *Expr) GetWildcard() *Wildcard {
	if x != nil {
		if x, ok := x.Kind.(*Expr_Wildcard); ok {
			return x.Wildcard
		}
	}
	return nil
}

func (x *Expr) GetExclude() *Exclude {
	if x != nil {
		if x, ok := x.Kind.(*Expr_Exclude); ok {
			return x.Exclude
		}
	}
	return nil
}

func (x *Expr) GetCast() *Cast {
	if x != nil {
		if x, ok := x.Kind.(*Expr_Cast); ok {
			return x.Cast
		}
	}
	return nil
}

func (x *Expr) GetStrLenBytes() *StringFunction {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrLenBytes); ok {
			return x.StrLenBytes
		}
	}
	return nil
}

func (x *Expr) GetStrLenChars() *StringFunction {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrLenChars); ok {
			return x.StrLenChars
		}
	}
	return nil
}

func (x *Expr) GetStrContains() *StringContains {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrContains); ok {
			return x.StrContains
		}
	}
	return nil
}

func (x *Expr) GetStrStartsWith() *StringStartsWith {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrStartsWith); ok {
			return x.StrStartsWith
		}
	}
	return nil
}

func (x *Expr) GetStrEndsWith() *StringEndsWith {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrEndsWith); ok {
			return x.StrEndsWith
		}
	}
	return nil
}

func (x *Expr) GetStrExtract() *StringExtract {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrExtract); ok {
			return x.StrExtract
		}
	}
	return nil
}

func (x *Expr) GetStrReplace() *StringReplace {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrReplace); ok {
			return x.StrReplace
		}
	}
	return nil
}

func (x *Expr) GetStrReplaceAll() *StringReplace {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrReplaceAll); ok {
			return x.StrReplaceAll
		}
	}
	return nil
}

func (x *Expr) GetStrToLowercase() *StringFunction {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrToLowercase); ok {
			return x.StrToLowercase
		}
	}
	return nil
}

func (x *Expr) GetStrToUppercase() *StringFunction {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrToUppercase); ok {
			return x.StrToUppercase
		}
	}
	return nil
}

func (x *Expr) GetStrToTitlecase() *StringFunction {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrToTitlecase); ok {
			return x.StrToTitlecase
		}
	}
	return nil
}

func (x *Expr) GetStrStripChars() *StringStripChars {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrStripChars); ok {
			return x.StrStripChars
		}
	}
	return nil
}

func (x *Expr) GetStrSlice() *StringSlice {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrSlice); ok {
			return x.StrSlice
		}
	}
	return nil
}

func (x *Expr) GetStrSplit() *StringSplit {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrSplit); ok {
			return x.StrSplit
		}
	}
	return nil
}

func (x *Expr) GetStrPadStart() *StringPad {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrPadStart); ok {
			return x.StrPadStart
		}
	}
	return nil
}

func (x *Expr) GetStrPadEnd() *StringPad {
	if x != nil {
		if x, ok := x.Kind.(*Expr_StrPadEnd); ok {
			return x.StrPadEnd
		}
	}
	return nil
}

type isExpr_Kind interface {
	isExpr_Kind()
}

type Expr_Col struct {
	Col *Column `protobuf:"bytes,1,opt,name=col,proto3,oneof"`
}

type Expr_Lit struct {
	Lit *Literal `protobuf:"bytes,2,opt,name=lit,proto3,oneof"`
}

type Expr_Binary struct {
	Binary *BinaryExpr `protobuf:"bytes,3,opt,name=binary,proto3,oneof"`
}

type Expr_Alias struct {
	Alias *Alias `protobuf:"bytes,4,opt,name=alias,proto3,oneof"`
}

type Expr_IsNull struct {
	IsNull *IsNull `protobuf:"bytes,5,opt,name=is_null,json=isNull,proto3,oneof"`
}

type Expr_Not struct {
	Not *Not `protobuf:"bytes,6,opt,name=not,proto3,oneof"` // 逻辑取反
}

type Expr_Wildcard struct {
	Wildcard *Wildcard `protobuf:"bytes,7,opt,name=wildcard,proto3,oneof"` // 通配符（选择所有列）
}

type Expr_Exclude struct {
	Exclude *Exclude `protobuf:"bytes,8,opt,name=exclude,proto3,oneof"` // 排除列
}

type Expr_Cast struct {
	Cast *Cast `protobuf:"bytes,9,opt,name=cast,proto3,oneof"` // 类型转换
}

type Expr_StrLenBytes struct {
	// 字符串函数 (50-99)
	StrLenBytes *StringFunction `protobuf:"bytes,50,opt,name=str_len_bytes,json=strLenBytes,proto3,oneof"`
}

type Expr_StrLenChars struct {
	StrLenChars *StringFunction `protobuf:"bytes,51,opt,name=str_len_chars,json=strLenChars,proto3,oneof"`
}

type Expr_StrContains struct {
	StrContains *StringContains `protobuf:"bytes,52,opt,name=str_contains,json=strContains,proto3,oneof"`
}

type Expr_StrStartsWith struct {
	StrStartsWith *StringStartsWith `protobuf:"bytes,53,opt,name=str_starts_with,json=strStartsWith,proto3,oneof"`
}

type Expr_StrEndsWith struct {
	StrEndsWith *StringEndsWith `protobuf:"bytes,54,opt,name=str_ends_with,json=strEndsWith,proto3,oneof"`
}

type Expr_StrExtract struct {
	StrExtract *StringExtract `protobuf:"bytes,55,opt,name=str_extract,json=strExtract,proto3,oneof"`
}

type Expr_StrReplace struct {
	StrReplace *StringReplace `protobuf:"bytes,56,opt,name=str_replace,json=strReplace,proto3,oneof"`
}

type Expr_StrReplaceAll struct {
	StrReplaceAll *StringReplace `protobuf:"bytes,57,opt,name=str_replace_all,json=strReplaceAll,proto3,oneof"`
}

type Expr_StrToLowercase struct {
	StrToLowercase *StringFunction `protobuf:"bytes,58,opt,name=str_to_lowercase,json=strToLowercase,proto3,oneof"`
}

type Expr_StrToUppercase struct {
	StrToUppercase *StringFunction `protobuf:"bytes,59,opt,name=str_to_uppercase,json=strToUppercase,proto3,oneof"`
}

type Expr_StrToTitlecase struct {
	StrToTitlecase *StringFunction `protobuf:"bytes,60,opt,name=str_to_titlecase,json=strToTitlecase,proto3,oneof"`
}

type Expr_StrStripChars struct {
	StrStripChars *StringStripChars `protobuf:"bytes,61,opt,name=str_strip_chars,json=strStripChars,proto3,oneof"`
}

type Expr_StrSlice struct {
	StrSlice *StringSlice `protobuf:"bytes,62,opt,name=str_slice,json=strSlice,proto3,oneof"`
}

type Expr_StrSplit struct {
	StrSplit *StringSplit `protobuf:"bytes,63,opt,name=str_split,json=strSplit,proto3,oneof"`
}

type Expr_StrPadStart struct {
	StrPadStart *StringPad `protobuf:"bytes,64,opt,name=str_pad_start,json=strPadStart,proto3,oneof"`
}

type Expr_StrPadEnd struct {
	StrPadEnd *StringPad `protobuf:"bytes,65,opt,name=str_pad_end,json=strPadEnd,proto3,oneof"`
}

func (*Expr_Col) isExpr_Kind() {}

func (*Expr_Lit) isExpr_Kind() {}

func (*Expr_Binary) isExpr_Kind() {}

func (*Expr_Alias) isExpr_Kind() {}

func (*Expr_IsNull) isExpr_Kind() {}

func (*Expr_Not) isExpr_Kind() {}

func (*Expr_Wildcard) isExpr_Kind() {}

func (*Expr_Exclude) isExpr_Kind() {}

func (*Expr_Cast) isExpr_Kind() {}

func (*Expr_StrLenBytes) isExpr_Kind() {}

func (*Expr_StrLenChars) isExpr_Kind() {}

func (*Expr_StrContains) isExpr_Kind() {}

func (*Expr_StrStartsWith) isExpr_Kind() {}

func (*Expr_StrEndsWith) isExpr_Kind() {}

func (*Expr_StrExtract) isExpr_Kind() {}

func (*Expr_StrReplace) isExpr_Kind() {}

func (*Expr_StrReplaceAll) isExpr_Kind() {}

func (*Expr_StrToLowercase) isExpr_Kind() {}

func (*Expr_StrToUppercase) isExpr_Kind() {}

func (*Expr_StrToTitlecase) isExpr_Kind() {}

func (*Expr_StrStripChars) isExpr_Kind() {}

func (*Expr_StrSlice) isExpr_Kind() {}

func (*Expr_StrSplit) isExpr_Kind() {}

func (*Expr_StrPadStart) isExpr_Kind() {}

func (*Expr_StrPadEnd) isExpr_Kind() {}

// 列引用
type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_proto_polars_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 字面量
type Literal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Literal_IntVal
	//	*Literal_FloatVal
	//	*Literal_BoolVal
	//	*Literal_StringVal
	//	*Literal_NullVal
	Value         isLiteral_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Literal) Reset() {
	*x = Literal{}
	mi := &file_proto_polars_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Literal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Literal) ProtoMessage() {}

func (x *Literal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Literal.ProtoReflect.Descriptor instead.
func (*Literal) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *Literal) GetValue() isLiteral_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Literal) GetIntVal() int64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_IntVal); ok {
			return x.IntVal
		}
	}
	return 0
}

func (x *Literal) GetFloatVal() float64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_FloatVal); ok {
			return x.FloatVal
		}
	}
	return 0
}

func (x *Literal) GetBoolVal() bool {
	if x != nil {
		if x, ok := x.Value.(*Literal_BoolVal); ok {
			return x.BoolVal
		}
	}
	return false
}

func (x *Literal) GetStringVal() string {
	if x != nil {
		if x, ok := x.Value.(*Literal_StringVal); ok {
			return x.StringVal
		}
	}
	return ""
}

func (x *Literal) GetNullVal() *NullValue {
	if x != nil {
		if x, ok := x.Value.(*Literal_NullVal); ok {
			return x.NullVal
		}
	}
	return nil
}

type isLiteral_Value interface {
	isLiteral_Value()
}

type Literal_IntVal struct {
	IntVal int64 `protobuf:"varint,1,opt,name=int_val,json=intVal,proto3,oneof"`
}

type Literal_FloatVal struct {
	FloatVal float64 `protobuf:"fixed64,2,opt,name=float_val,json=floatVal,proto3,oneof"`
}

type Literal_BoolVal struct {
	BoolVal bool `protobuf:"varint,3,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

type Literal_StringVal struct {
	StringVal string `protobuf:"bytes,4,opt,name=string_val,json=stringVal,proto3,oneof"`
}

type Literal_NullVal struct {
	NullVal *NullValue `protobuf:"bytes,5,opt,name=null_val,json=nullVal,proto3,oneof"`
}

func (*Literal_IntVal) isLiteral_Value() {}

func (*Literal_FloatVal) isLiteral_Value() {}

func (*Literal_BoolVal) isLiteral_Value() {}

func (*Literal_StringVal) isLiteral_Value() {}

func (*Literal_NullVal) isLiteral_Value() {}

type NullValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullValue) Reset() {
	*x = NullValue{}
	mi := &file_proto_polars_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullValue) ProtoMessage() {}

func (x *NullValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullValue.ProtoReflect.Descriptor instead.
func (*NullValue) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{12}
}

// 二元表达式
type BinaryExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          *Expr                  `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Op            BinaryOperator         `protobuf:"varint,2,opt,name=op,proto3,enum=polars_bridge.BinaryOperator" json:"op,omitempty"`
	Right         *Expr                  `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryExpr) Reset() {
	*x = BinaryExpr{}
	mi := &file_proto_polars_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryExpr) ProtoMessage() {}

func (x *BinaryExpr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryExpr.ProtoReflect.Descriptor instead.
func (*BinaryExpr) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *BinaryExpr) GetLeft() *Expr {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *BinaryExpr) GetOp() BinaryOperator {
	if x != nil {
		return x.Op
	}
	return BinaryOperator_ADD
}

func (x *BinaryExpr) GetRight() *Expr {
	if x != nil {
		return x.Right
	}
	return nil
}

// 别名
type Alias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alias) Reset() {
	*x = Alias{}
	mi := &file_proto_polars_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alias) ProtoMessage() {}

func (x *Alias) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alias.ProtoReflect.Descriptor instead.
func (*Alias) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *Alias) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Alias) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 空值检查
type IsNull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsNull) Reset() {
	*x = IsNull{}
	mi := &file_proto_polars_bridge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsNull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsNull) ProtoMessage() {}

func (x *IsNull) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsNull.ProtoReflect.Descriptor instead.
func (*IsNull) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{15}
}

func (x *IsNull) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

// 逻辑取反
type Not struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Not) Reset() {
	*x = Not{}
	mi := &file_proto_polars_bridge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Not) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Not) ProtoMessage() {}

func (x *Not) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Not.ProtoReflect.Descriptor instead.
func (*Not) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{16}
}

func (x *Not) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

// 通配符（选择所有列）
type Wildcard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wildcard) Reset() {
	*x = Wildcard{}
	mi := &file_proto_polars_bridge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wildcard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wildcard) ProtoMessage() {}

func (x *Wildcard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wildcard.ProtoReflect.Descriptor instead.
func (*Wildcard) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{17}
}

// 排除列
type Exclude struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`       // 基础表达式（通常是 Wildcard）
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"` // 要排除的列名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exclude) Reset() {
	*x = Exclude{}
	mi := &file_proto_polars_bridge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exclude) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exclude) ProtoMessage() {}

func (x *Exclude) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exclude.ProtoReflect.Descriptor instead.
func (*Exclude) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{18}
}

func (x *Exclude) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Exclude) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

// 类型转换
type Cast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`                                                      // 要转换的表达式
	DataType      DataType               `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3,enum=polars_bridge.DataType" json:"data_type,omitempty"` // 目标数据类型
	Strict        bool                   `protobuf:"varint,3,opt,name=strict,proto3" json:"strict,omitempty"`                                                 // 严格模式（默认 true）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cast) Reset() {
	*x = Cast{}
	mi := &file_proto_polars_bridge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cast) ProtoMessage() {}

func (x *Cast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cast.ProtoReflect.Descriptor instead.
func (*Cast) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{19}
}

func (x *Cast) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Cast) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_INT64
}

func (x *Cast) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

// 通用字符串函数（单一表达式）
type StringFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringFunction) Reset() {
	*x = StringFunction{}
	mi := &file_proto_polars_bridge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringFunction) ProtoMessage() {}

func (x *StringFunction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringFunction.ProtoReflect.Descriptor instead.
func (*StringFunction) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{20}
}

func (x *StringFunction) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

// 字符串包含检查
type StringContains struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Literal       bool                   `protobuf:"varint,3,opt,name=literal,proto3" json:"literal,omitempty"` // true: 字面字符串, false: 正则表达式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringContains) Reset() {
	*x = StringContains{}
	mi := &file_proto_polars_bridge_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringContains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringContains) ProtoMessage() {}

func (x *StringContains) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringContains.ProtoReflect.Descriptor instead.
func (*StringContains) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{21}
}

func (x *StringContains) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *StringContains) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *StringContains) GetLiteral() bool {
	if x != nil {
		return x.Literal
	}
	return false
}

// 字符串前缀检查
type StringStartsWith struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringStartsWith) Reset() {
	*x = StringStartsWith{}
	mi := &file_proto_polars_bridge_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringStartsWith) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringStartsWith) ProtoMessage() {}

func (x *StringStartsWith) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringStartsWith.ProtoReflect.Descriptor instead.
func (*StringStartsWith) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{22}
}

func (x *StringStartsWith) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *StringStartsWith) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

// 字符串后缀检查
type StringEndsWith struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Suffix        string                 `protobuf:"bytes,2,opt,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringEndsWith) Reset() {
	*x = StringEndsWith{}
	mi := &file_proto_polars_bridge_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringEndsWith) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringEndsWith) ProtoMessage() {}

func (x *StringEndsWith) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringEndsWith.ProtoReflect.Descriptor instead.
func (*StringEndsWith) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{23}
}

func (x *StringEndsWith) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *StringEndsWith) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

// 字符串提取（正则）
type StringExtract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	GroupIndex    uint32                 `protobuf:"varint,3,opt,name=group_index,json=groupIndex,proto3" json:"group_index,omitempty"` // 捕获组索引
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringExtract) Reset() {
	*x = StringExtract{}
	mi := &file_proto_polars_bridge_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringExtract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringExtract) ProtoMessage() {}

func (x *StringExtract) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringExtract.ProtoReflect.Descriptor instead.
func (*StringExtract) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{24}
}

func (x *StringExtract) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *StringExtract) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *StringExtract) GetGroupIndex() uint32 {
	if x != nil {
		return x.GroupIndex
	}
	return 0
}

// 字符串替换
type StringReplace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Literal       bool                   `protobuf:"varint,4,opt,name=literal,proto3" json:"literal,omitempty"` // true: 字面字符串, false: 正则表达式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringReplace) Reset() {
	*x = StringReplace{}
	mi := &file_proto_polars_bridge_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringReplace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringReplace) ProtoMessage() {}

func (x *StringReplace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringReplace.ProtoReflect.Descriptor instead.
func (*StringReplace) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{25}
}

func (x *StringReplace) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *StringReplace) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *StringReplace) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StringReplace) GetLiteral() bool {
	if x != nil {
		return x.Literal
	}
	return false
}

// 字符串修剪
type StringStripChars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Chars         string                 `protobuf:"bytes,2,opt,name=chars,proto3" json:"chars,omitempty"` // 要移除的字符，空字符串表示移除空白字符
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringStripChars) Reset() {
	*x = StringStripChars{}
	mi := &file_proto_polars_bridge_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringStripChars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringStripChars) ProtoMessage() {}

func (x *StringStripChars) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringStripChars.ProtoReflect.Descriptor instead.
func (*StringStripChars) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{26}
}

func (x *StringStripChars) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *StringStripChars) GetChars() string {
	if x != nil {
		return x.Chars
	}
	return ""
}

// 字符串切片
type StringSlice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`       // 起始位置（可为负数）
	Length        *uint64                `protobuf:"varint,3,opt,name=length,proto3,oneof" json:"length,omitempty"` // 长度（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringSlice) Reset() {
	*x = StringSlice{}
	mi := &file_proto_polars_bridge_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringSlice) ProtoMessage() {}

func (x *StringSlice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringSlice.ProtoReflect.Descriptor instead.
func (*StringSlice) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{27}
}

func (x *StringSlice) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *StringSlice) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StringSlice) GetLength() uint64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

// 字符串分割
type StringSplit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	By            string                 `protobuf:"bytes,2,opt,name=by,proto3" json:"by,omitempty"` // 分隔符
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringSplit) Reset() {
	*x = StringSplit{}
	mi := &file_proto_polars_bridge_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringSplit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringSplit) ProtoMessage() {}

func (x *StringSplit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringSplit.ProtoReflect.Descriptor instead.
func (*StringSplit) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{28}
}

func (x *StringSplit) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *StringSplit) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

// 字符串填充
type StringPad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          *Expr                  `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Length        uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`                    // 目标长度
	FillChar      string                 `protobuf:"bytes,3,opt,name=fill_char,json=fillChar,proto3" json:"fill_char,omitempty"` // 填充字符
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringPad) Reset() {
	*x = StringPad{}
	mi := &file_proto_polars_bridge_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringPad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPad) ProtoMessage() {}

func (x *StringPad) ProtoReflect() protoreflect.Message {
	mi := &file_proto_polars_bridge_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPad.ProtoReflect.Descriptor instead.
func (*StringPad) Descriptor() ([]byte, []int) {
	return file_proto_polars_bridge_proto_rawDescGZIP(), []int{29}
}

func (x *StringPad) GetExpr() *Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *StringPad) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *StringPad) GetFillChar() string {
	if x != nil {
		return x.FillChar
	}
	return ""
}

var File_proto_polars_bridge_proto protoreflect.FileDescriptor

const file_proto_polars_bridge_proto_rawDesc = "" +
	"\n" +
	"\x19proto/polars_bridge.proto\x12\rpolars_bridge\"R\n" +
	"\x04Plan\x12!\n" +
	"\fplan_version\x18\x01 \x01(\rR\vplanVersion\x12'\n" +
	"\x04root\x18\x02 \x01(\v2\x13.polars_bridge.NodeR\x04root\"\xb3\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12<\n" +
	"\vmemory_scan\x18\n" +
	" \x01(\v2\x19.polars_bridge.MemoryScanH\x00R\n" +
	"memoryScan\x123\n" +
	"\bcsv_scan\x18\v \x01(\v2\x16.polars_bridge.CsvScanH\x00R\acsvScan\x12?\n" +
	"\fparquet_scan\x18\f \x01(\v2\x1a.polars_bridge.ParquetScanH\x00R\vparquetScan\x122\n" +
	"\aproject\x18\r \x01(\v2\x16.polars_bridge.ProjectH\x00R\aproject\x12/\n" +
	"\x06filter\x18\x0e \x01(\v2\x15.polars_bridge.FilterH\x00R\x06filter\x12?\n" +
	"\fwith_columns\x18\x0f \x01(\v2\x1a.polars_bridge.WithColumnsH\x00R\vwithColumns\x12,\n" +
	"\x05limit\x18\x10 \x01(\v2\x14.polars_bridge.LimitH\x00R\x05limitB\x06\n" +
	"\x04kindJ\x04\b2\x10dJ\x05\bd\x10\x96\x01\"/\n" +
	"\n" +
	"MemoryScan\x12!\n" +
	"\fcolumn_names\x18\x01 \x03(\tR\vcolumnNames\"\x1d\n" +
	"\aCsvScan\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"!\n" +
	"\vParquetScan\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"k\n" +
	"\aProject\x12)\n" +
	"\x05input\x18\x01 \x01(\v2\x13.polars_bridge.NodeR\x05input\x125\n" +
	"\vexpressions\x18\x02 \x03(\v2\x13.polars_bridge.ExprR\vexpressions\"f\n" +
	"\x06Filter\x12)\n" +
	"\x05input\x18\x01 \x01(\v2\x13.polars_bridge.NodeR\x05input\x121\n" +
	"\tpredicate\x18\x02 \x01(\v2\x13.polars_bridge.ExprR\tpredicate\"o\n" +
	"\vWithColumns\x12)\n" +
	"\x05input\x18\x01 \x01(\v2\x13.polars_bridge.NodeR\x05input\x125\n" +
	"\vexpressions\x18\x02 \x03(\v2\x13.polars_bridge.ExprR\vexpressions\"@\n" +
	"\x05Limit\x12)\n" +
	"\x05input\x18\x01 \x01(\v2\x13.polars_bridge.NodeR\x05input\x12\f\n" +
	"\x01n\x18\x02 \x01(\x04R\x01n\"\x8b\f\n" +
	"\x04Expr\x12)\n" +
	"\x03col\x18\x01 \x01(\v2\x15.polars_bridge.ColumnH\x00R\x03col\x12*\n" +
	"\x03lit\x18\x02 \x01(\v2\x16.polars_bridge.LiteralH\x00R\x03lit\x123\n" +
	"\x06binary\x18\x03 \x01(\v2\x19.polars_bridge.BinaryExprH\x00R\x06binary\x12,\n" +
	"\x05alias\x18\x04 \x01(\v2\x14.polars_bridge.AliasH\x00R\x05alias\x120\n" +
	"\ais_null\x18\x05 \x01(\v2\x15.polars_bridge.IsNullH\x00R\x06isNull\x12&\n" +
	"\x03not\x18\x06 \x01(\v2\x12.polars_bridge.NotH\x00R\x03not\x125\n" +
	"\bwildcard\x18\a \x01(\v2\x17.polars_bridge.WildcardH\x00R\bwildcard\x122\n" +
	"\aexclude\x18\b \x01(\v2\x16.polars_bridge.ExcludeH\x00R\aexclude\x12)\n" +
	"\x04cast\x18\t \x01(\v2\x13.polars_bridge.CastH\x00R\x04cast\x12C\n" +
	"\rstr_len_bytes\x182 \x01(\v2\x1d.polars_bridge.StringFunctionH\x00R\vstrLenBytes\x12C\n" +
	"\rstr_len_chars\x183 \x01(\v2\x1d.polars_bridge.StringFunctionH\x00R\vstrLenChars\x12B\n" +
	"\fstr_contains\x184 \x01(\v2\x1d.polars_bridge.StringContainsH\x00R\vstrContains\x12I\n" +
	"\x0fstr_starts_with\x185 \x01(\v2\x1f.polars_bridge.StringStartsWithH\x00R\rstrStartsWith\x12C\n" +
	"\rstr_ends_with\x186 \x01(\v2\x1d.polars_bridge.StringEndsWithH\x00R\vstrEndsWith\x12?\n" +
	"\vstr_extract\x187 \x01(\v2\x1c.polars_bridge.StringExtractH\x00R\n" +
	"strExtract\x12?\n" +
	"\vstr_replace\x188 \x01(\v2\x1c.polars_bridge.StringReplaceH\x00R\n" +
	"strReplace\x12F\n" +
	"\x0fstr_replace_all\x189 \x01(\v2\x1c.polars_bridge.StringReplaceH\x00R\rstrReplaceAll\x12I\n" +
	"\x10str_to_lowercase\x18: \x01(\v2\x1d.polars_bridge.StringFunctionH\x00R\x0estrToLowercase\x12I\n" +
	"\x10str_to_uppercase\x18; \x01(\v2\x1d.polars_bridge.StringFunctionH\x00R\x0estrToUppercase\x12I\n" +
	"\x10str_to_titlecase\x18< \x01(\v2\x1d.polars_bridge.StringFunctionH\x00R\x0estrToTitlecase\x12I\n" +
	"\x0fstr_strip_chars\x18= \x01(\v2\x1f.polars_bridge.StringStripCharsH\x00R\rstrStripChars\x129\n" +
	"\tstr_slice\x18> \x01(\v2\x1a.polars_bridge.StringSliceH\x00R\bstrSlice\x129\n" +
	"\tstr_split\x18? \x01(\v2\x1a.polars_bridge.StringSplitH\x00R\bstrSplit\x12>\n" +
	"\rstr_pad_start\x18@ \x01(\v2\x18.polars_bridge.StringPadH\x00R\vstrPadStart\x12:\n" +
	"\vstr_pad_end\x18A \x01(\v2\x18.polars_bridge.StringPadH\x00R\tstrPadEndB\x06\n" +
	"\x04kindJ\x04\bB\x10dJ\x05\bd\x10\x96\x01\"\x1c\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc1\x01\n" +
	"\aLiteral\x12\x19\n" +
	"\aint_val\x18\x01 \x01(\x03H\x00R\x06intVal\x12\x1d\n" +
	"\tfloat_val\x18\x02 \x01(\x01H\x00R\bfloatVal\x12\x1b\n" +
	"\bbool_val\x18\x03 \x01(\bH\x00R\aboolVal\x12\x1f\n" +
	"\n" +
	"string_val\x18\x04 \x01(\tH\x00R\tstringVal\x125\n" +
	"\bnull_val\x18\x05 \x01(\v2\x18.polars_bridge.NullValueH\x00R\anullValB\a\n" +
	"\x05value\"\v\n" +
	"\tNullValue\"\x8f\x01\n" +
	"\n" +
	"BinaryExpr\x12'\n" +
	"\x04left\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04left\x12-\n" +
	"\x02op\x18\x02 \x01(\x0e2\x1d.polars_bridge.BinaryOperatorR\x02op\x12)\n" +
	"\x05right\x18\x03 \x01(\v2\x13.polars_bridge.ExprR\x05right\"D\n" +
	"\x05Alias\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"1\n" +
	"\x06IsNull\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\".\n" +
	"\x03Not\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\"\n" +
	"\n" +
	"\bWildcard\"L\n" +
	"\aExclude\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\"}\n" +
	"\x04Cast\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x124\n" +
	"\tdata_type\x18\x02 \x01(\x0e2\x17.polars_bridge.DataTypeR\bdataType\x12\x16\n" +
	"\x06strict\x18\x03 \x01(\bR\x06strict\"9\n" +
	"\x0eStringFunction\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\"m\n" +
	"\x0eStringContains\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x18\n" +
	"\aliteral\x18\x03 \x01(\bR\aliteral\"S\n" +
	"\x10StringStartsWith\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"Q\n" +
	"\x0eStringEndsWith\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x12\x16\n" +
	"\x06suffix\x18\x02 \x01(\tR\x06suffix\"s\n" +
	"\rStringExtract\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x1f\n" +
	"\vgroup_index\x18\x03 \x01(\rR\n" +
	"groupIndex\"\x82\x01\n" +
	"\rStringReplace\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x18\n" +
	"\aliteral\x18\x04 \x01(\bR\aliteral\"Q\n" +
	"\x10StringStripChars\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x12\x14\n" +
	"\x05chars\x18\x02 \x01(\tR\x05chars\"v\n" +
	"\vStringSlice\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1b\n" +
	"\x06length\x18\x03 \x01(\x04H\x00R\x06length\x88\x01\x01B\t\n" +
	"\a_length\"F\n" +
	"\vStringSplit\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x12\x0e\n" +
	"\x02by\x18\x02 \x01(\tR\x02by\"i\n" +
	"\tStringPad\x12'\n" +
	"\x04expr\x18\x01 \x01(\v2\x13.polars_bridge.ExprR\x04expr\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x1b\n" +
	"\tfill_char\x18\x03 \x01(\tR\bfillChar*\x90\x01\n" +
	"\x0eBinaryOperator\x12\a\n" +
	"\x03ADD\x10\x00\x12\a\n" +
	"\x03SUB\x10\x01\x12\a\n" +
	"\x03MUL\x10\x02\x12\a\n" +
	"\x03DIV\x10\x03\x12\x06\n" +
	"\x02EQ\x10\x04\x12\x06\n" +
	"\x02NE\x10\x05\x12\x06\n" +
	"\x02LT\x10\x06\x12\x06\n" +
	"\x02LE\x10\a\x12\x06\n" +
	"\x02GT\x10\b\x12\x06\n" +
	"\x02GE\x10\t\x12\a\n" +
	"\x03AND\x10\n" +
	"\x12\x06\n" +
	"\x02OR\x10\v\x12\a\n" +
	"\x03MOD\x10\f\x12\a\n" +
	"\x03POW\x10\r\x12\a\n" +
	"\x03XOR\x10\x0e*\xb4\x01\n" +
	"\bDataType\x12\t\n" +
	"\x05INT64\x10\x00\x12\t\n" +
	"\x05INT32\x10\x01\x12\t\n" +
	"\x05INT16\x10\x02\x12\b\n" +
	"\x04INT8\x10\x03\x12\n" +
	"\n" +
	"\x06UINT64\x10\x04\x12\n" +
	"\n" +
	"\x06UINT32\x10\x05\x12\n" +
	"\n" +
	"\x06UINT16\x10\x06\x12\t\n" +
	"\x05UINT8\x10\a\x12\v\n" +
	"\aFLOAT64\x10\b\x12\v\n" +
	"\aFLOAT32\x10\t\x12\b\n" +
	"\x04BOOL\x10\n" +
	"\x12\b\n" +
	"\x04UTF8\x10\v\x12\b\n" +
	"\x04DATE\x10\f\x12\f\n" +
	"\bDATETIME\x10\r\x12\b\n" +
	"\x04TIME\x10\x0eB#Z!github.com/polars-go-bridge/protob\x06proto3"

var (
	file_proto_polars_bridge_proto_rawDescOnce sync.Once
	file_proto_polars_bridge_proto_rawDescData []byte
)

func file_proto_polars_bridge_proto_rawDescGZIP() []byte {
	file_proto_polars_bridge_proto_rawDescOnce.Do(func() {
		file_proto_polars_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_polars_bridge_proto_rawDesc), len(file_proto_polars_bridge_proto_rawDesc)))
	})
	return file_proto_polars_bridge_proto_rawDescData
}

var file_proto_polars_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_polars_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_polars_bridge_proto_goTypes = []any{
	(BinaryOperator)(0),      // 0: polars_bridge.BinaryOperator
	(DataType)(0),            // 1: polars_bridge.DataType
	(*Plan)(nil),             // 2: polars_bridge.Plan
	(*Node)(nil),             // 3: polars_bridge.Node
	(*MemoryScan)(nil),       // 4: polars_bridge.MemoryScan
	(*CsvScan)(nil),          // 5: polars_bridge.CsvScan
	(*ParquetScan)(nil),      // 6: polars_bridge.ParquetScan
	(*Project)(nil),          // 7: polars_bridge.Project
	(*Filter)(nil),           // 8: polars_bridge.Filter
	(*WithColumns)(nil),      // 9: polars_bridge.WithColumns
	(*Limit)(nil),            // 10: polars_bridge.Limit
	(*Expr)(nil),             // 11: polars_bridge.Expr
	(*Column)(nil),           // 12: polars_bridge.Column
	(*Literal)(nil),          // 13: polars_bridge.Literal
	(*NullValue)(nil),        // 14: polars_bridge.NullValue
	(*BinaryExpr)(nil),       // 15: polars_bridge.BinaryExpr
	(*Alias)(nil),            // 16: polars_bridge.Alias
	(*IsNull)(nil),           // 17: polars_bridge.IsNull
	(*Not)(nil),              // 18: polars_bridge.Not
	(*Wildcard)(nil),         // 19: polars_bridge.Wildcard
	(*Exclude)(nil),          // 20: polars_bridge.Exclude
	(*Cast)(nil),             // 21: polars_bridge.Cast
	(*StringFunction)(nil),   // 22: polars_bridge.StringFunction
	(*StringContains)(nil),   // 23: polars_bridge.StringContains
	(*StringStartsWith)(nil), // 24: polars_bridge.StringStartsWith
	(*StringEndsWith)(nil),   // 25: polars_bridge.StringEndsWith
	(*StringExtract)(nil),    // 26: polars_bridge.StringExtract
	(*StringReplace)(nil),    // 27: polars_bridge.StringReplace
	(*StringStripChars)(nil), // 28: polars_bridge.StringStripChars
	(*StringSlice)(nil),      // 29: polars_bridge.StringSlice
	(*StringSplit)(nil),      // 30: polars_bridge.StringSplit
	(*StringPad)(nil),        // 31: polars_bridge.StringPad
}
var file_proto_polars_bridge_proto_depIdxs = []int32{
	3,  // 0: polars_bridge.Plan.root:type_name -> polars_bridge.Node
	4,  // 1: polars_bridge.Node.memory_scan:type_name -> polars_bridge.MemoryScan
	5,  // 2: polars_bridge.Node.csv_scan:type_name -> polars_bridge.CsvScan
	6,  // 3: polars_bridge.Node.parquet_scan:type_name -> polars_bridge.ParquetScan
	7,  // 4: polars_bridge.Node.project:type_name -> polars_bridge.Project
	8,  // 5: polars_bridge.Node.filter:type_name -> polars_bridge.Filter
	9,  // 6: polars_bridge.Node.with_columns:type_name -> polars_bridge.WithColumns
	10, // 7: polars_bridge.Node.limit:type_name -> polars_bridge.Limit
	3,  // 8: polars_bridge.Project.input:type_name -> polars_bridge.Node
	11, // 9: polars_bridge.Project.expressions:type_name -> polars_bridge.Expr
	3,  // 10: polars_bridge.Filter.input:type_name -> polars_bridge.Node
	11, // 11: polars_bridge.Filter.predicate:type_name -> polars_bridge.Expr
	3,  // 12: polars_bridge.WithColumns.input:type_name -> polars_bridge.Node
	11, // 13: polars_bridge.WithColumns.expressions:type_name -> polars_bridge.Expr
	3,  // 14: polars_bridge.Limit.input:type_name -> polars_bridge.Node
	12, // 15: polars_bridge.Expr.col:type_name -> polars_bridge.Column
	13, // 16: polars_bridge.Expr.lit:type_name -> polars_bridge.Literal
	15, // 17: polars_bridge.Expr.binary:type_name -> polars_bridge.BinaryExpr
	16, // 18: polars_bridge.Expr.alias:type_name -> polars_bridge.Alias
	17, // 19: polars_bridge.Expr.is_null:type_name -> polars_bridge.IsNull
	18, // 20: polars_bridge.Expr.not:type_name -> polars_bridge.Not
	19, // 21: polars_bridge.Expr.wildcard:type_name -> polars_bridge.Wildcard
	20, // 22: polars_bridge.Expr.exclude:type_name -> polars_bridge.Exclude
	21, // 23: polars_bridge.Expr.cast:type_name -> polars_bridge.Cast
	22, // 24: polars_bridge.Expr.str_len_bytes:type_name -> polars_bridge.StringFunction
	22, // 25: polars_bridge.Expr.str_len_chars:type_name -> polars_bridge.StringFunction
	23, // 26: polars_bridge.Expr.str_contains:type_name -> polars_bridge.StringContains
	24, // 27: polars_bridge.Expr.str_starts_with:type_name -> polars_bridge.StringStartsWith
	25, // 28: polars_bridge.Expr.str_ends_with:type_name -> polars_bridge.StringEndsWith
	26, // 29: polars_bridge.Expr.str_extract:type_name -> polars_bridge.StringExtract
	27, // 30: polars_bridge.Expr.str_replace:type_name -> polars_bridge.StringReplace
	27, // 31: polars_bridge.Expr.str_replace_all:type_name -> polars_bridge.StringReplace
	22, // 32: polars_bridge.Expr.str_to_lowercase:type_name -> polars_bridge.StringFunction
	22, // 33: polars_bridge.Expr.str_to_uppercase:type_name -> polars_bridge.StringFunction
	22, // 34: polars_bridge.Expr.str_to_titlecase:type_name -> polars_bridge.StringFunction
	28, // 35: polars_bridge.Expr.str_strip_chars:type_name -> polars_bridge.StringStripChars
	29, // 36: polars_bridge.Expr.str_slice:type_name -> polars_bridge.StringSlice
	30, // 37: polars_bridge.Expr.str_split:type_name -> polars_bridge.StringSplit
	31, // 38: polars_bridge.Expr.str_pad_start:type_name -> polars_bridge.StringPad
	31, // 39: polars_bridge.Expr.str_pad_end:type_name -> polars_bridge.StringPad
	14, // 40: polars_bridge.Literal.null_val:type_name -> polars_bridge.NullValue
	11, // 41: polars_bridge.BinaryExpr.left:type_name -> polars_bridge.Expr
	0,  // 42: polars_bridge.BinaryExpr.op:type_name -> polars_bridge.BinaryOperator
	11, // 43: polars_bridge.BinaryExpr.right:type_name -> polars_bridge.Expr
	11, // 44: polars_bridge.Alias.expr:type_name -> polars_bridge.Expr
	11, // 45: polars_bridge.IsNull.expr:type_name -> polars_bridge.Expr
	11, // 46: polars_bridge.Not.expr:type_name -> polars_bridge.Expr
	11, // 47: polars_bridge.Exclude.expr:type_name -> polars_bridge.Expr
	11, // 48: polars_bridge.Cast.expr:type_name -> polars_bridge.Expr
	1,  // 49: polars_bridge.Cast.data_type:type_name -> polars_bridge.DataType
	11, // 50: polars_bridge.StringFunction.expr:type_name -> polars_bridge.Expr
	11, // 51: polars_bridge.StringContains.expr:type_name -> polars_bridge.Expr
	11, // 52: polars_bridge.StringStartsWith.expr:type_name -> polars_bridge.Expr
	11, // 53: polars_bridge.StringEndsWith.expr:type_name -> polars_bridge.Expr
	11, // 54: polars_bridge.StringExtract.expr:type_name -> polars_bridge.Expr
	11, // 55: polars_bridge.StringReplace.expr:type_name -> polars_bridge.Expr
	11, // 56: polars_bridge.StringStripChars.expr:type_name -> polars_bridge.Expr
	11, // 57: polars_bridge.StringSlice.expr:type_name -> polars_bridge.Expr
	11, // 58: polars_bridge.StringSplit.expr:type_name -> polars_bridge.Expr
	11, // 59: polars_bridge.StringPad.expr:type_name -> polars_bridge.Expr
	60, // [60:60] is the sub-list for method output_type
	60, // [60:60] is the sub-list for method input_type
	60, // [60:60] is the sub-list for extension type_name
	60, // [60:60] is the sub-list for extension extendee
	0,  // [0:60] is the sub-list for field type_name
}

func init() { file_proto_polars_bridge_proto_init() }
func file_proto_polars_bridge_proto_init() {
	if File_proto_polars_bridge_proto != nil {
		return
	}
	file_proto_polars_bridge_proto_msgTypes[1].OneofWrappers = []any{
		(*Node_MemoryScan)(nil),
		(*Node_CsvScan)(nil),
		(*Node_ParquetScan)(nil),
		(*Node_Project)(nil),
		(*Node_Filter)(nil),
		(*Node_WithColumns)(nil),
		(*Node_Limit)(nil),
	}
	file_proto_polars_bridge_proto_msgTypes[9].OneofWrappers = []any{
		(*Expr_Col)(nil),
		(*Expr_Lit)(nil),
		(*Expr_Binary)(nil),
		(*Expr_Alias)(nil),
		(*Expr_IsNull)(nil),
		(*Expr_Not)(nil),
		(*Expr_Wildcard)(nil),
		(*Expr_Exclude)(nil),
		(*Expr_Cast)(nil),
		(*Expr_StrLenBytes)(nil),
		(*Expr_StrLenChars)(nil),
		(*Expr_StrContains)(nil),
		(*Expr_StrStartsWith)(nil),
		(*Expr_StrEndsWith)(nil),
		(*Expr_StrExtract)(nil),
		(*Expr_StrReplace)(nil),
		(*Expr_StrReplaceAll)(nil),
		(*Expr_StrToLowercase)(nil),
		(*Expr_StrToUppercase)(nil),
		(*Expr_StrToTitlecase)(nil),
		(*Expr_StrStripChars)(nil),
		(*Expr_StrSlice)(nil),
		(*Expr_StrSplit)(nil),
		(*Expr_StrPadStart)(nil),
		(*Expr_StrPadEnd)(nil),
	}
	file_proto_polars_bridge_proto_msgTypes[11].OneofWrappers = []any{
		(*Literal_IntVal)(nil),
		(*Literal_FloatVal)(nil),
		(*Literal_BoolVal)(nil),
		(*Literal_StringVal)(nil),
		(*Literal_NullVal)(nil),
	}
	file_proto_polars_bridge_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_polars_bridge_proto_rawDesc), len(file_proto_polars_bridge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_polars_bridge_proto_goTypes,
		DependencyIndexes: file_proto_polars_bridge_proto_depIdxs,
		EnumInfos:         file_proto_polars_bridge_proto_enumTypes,
		MessageInfos:      file_proto_polars_bridge_proto_msgTypes,
	}.Build()
	File_proto_polars_bridge_proto = out.File
	file_proto_polars_bridge_proto_goTypes = nil
	file_proto_polars_bridge_proto_depIdxs = nil
}
